spring.data.mongodb.database: covid
covid.download.url: https://d20s4vd27d0hk0.cloudfront.net/
covid.download.url2: https://ga-covid19.ondemand.sas.com/static/js/main.js


---
spring.profiles: cloud

covid:
  index.path: /mnt/data/covid/index.json
  dirs:
    report.target: /mnt/data/reports/
    report.target.v2: /mnt/data/reports/v2/
    raw: /mnt/data/raw
    histogram: /mnt/data/histogram
server.port: 8080
logging.file.path: /mnt/data/covid/logs/

---
spring.profiles: local

covid:
  index.path: H:\dev\workingdir\covid\index.json
  dirs:
    report.target: H:\dev\workingdir\covid\reports
    report.target.v2: H:\dev\workingdir\covid\reports
    raw: H:\dev\workingdir\covid\raw
    histogram: H:\dev\workingdir\covid\histogram
server.port: 8080
logging.file.path: H:\dev\covid\logs\