spring.data.mongodb.database: covid
covid.download.url: https://d20s4vd27d0hk0.cloudfront.net/
covid.download.url2: https://ga-covid19.ondemand.sas.com/static/js/main.js


---
spring.profiles: cloud

covid:
  index.path: /mnt/data/covid/index.json
  dirs:
    reports:
      root: /mnt/data/reports/
      csv: /mnt/data/reports/v2/csv/
      json: /mnt/data/reports/v2/json/
    raw:
      v0: /mnt/data/raw/v0
      v1: /mnt/data/raw/v1
      v2: /mnt/data/raw/v2
      manual: /mnt/data/raw/manual
    filtered:
      epicurve.v1: /mnt/data/filteredjson/epicurve/v1
      epicurve.v2: /mnt/data/filteredjson/epicurve/v2
      healthcare: /mnt/data/filteredjson/healthcare
      overview.v1: /mnt/data/filteredjson/overview/v1
    histogram: /mnt/data/histogram
server.port: 8080
logging.file.path: /mnt/data/covid/logs/

---
spring.profiles: local

covid:
  index.path: H:\dev\workingdir\covid\index.json
  dirs:
    reports:
      root: H:\dev\workingdir\covid\reports
      csv: H:\dev\workingdir\covid\reports\csv
      json: H:\dev\workingdir\covid\reports\json
    raw:
      v0: H:\dev\workingdir\covid\raw\v0
      v1: H:\dev\workingdir\covid\raw\v1
      v2: H:\dev\workingdir\covid\raw\v2
      manual: H:\dev\workingdir\covid\raw\manual
    filtered:
      epicurve.v1: H:\dev\workingdir\covid\filtered\epicurve\v1
      epicurve.v2: H:\dev\workingdir\covid\filtered\epicurve\v2
      healthcare: H:\dev\workingdir\covid\filtered\healthcare
      overview.v1: H:\dev\workingdir\covid\filtered\overview\v1
    histogram: H:\dev\workingdir\covid\histogram
server.port: 8080
logging.file.path: H:\dev\covid\logs\