spring.data.mongodb.database: covid
covid.download.url: https://d20s4vd27d0hk0.cloudfront.net/
covid.download.url2: https://ga-covid19.ondemand.sas.com/static/js/main.js


---
spring.profiles: cloud

covid:
  index.path: /mnt/data/covid/index.json
  dirs:
    report.target: /mnt/data/reports/
    report.target.csv: /mnt/data/reports/csv/
    report.target.json: /mnt/data/reports/json/
    raw.v2: /mnt/data/raw/v2
    raw.v1: /mnt/data/raw/v1
    raw.manual: /mnt/data/raw/manual
    histogram: /mnt/data/histogram
server.port: 8080
logging.file.path: /mnt/data/covid/logs/

---
spring.profiles: local

covid:
  index.path: H:\dev\workingdir\covid\index.json
  dirs:
    report.target: H:\dev\workingdir\covid\reports
    report.target.csv: H:\dev\workingdir\covid\reports\csv
    report.target.json: H:\dev\workingdir\covid\reports\json
    raw.v2: H:\dev\workingdir\covid\raw\v2
    raw.v1: H:\dev\workingdir\covid\raw\v1
    raw.manual: H:\dev\workingdir\covid\raw\manual
    histogram: H:\dev\workingdir\covid\histogram
server.port: 8080
logging.file.path: H:\dev\covid\logs\