spring.data.mongodb.database: covid
covid.download.url: https://d20s4vd27d0hk0.cloudfront.net/
covid.download.url2: https://ga-covid19.ondemand.sas.com/static/js/main.js

covid.histogram.window.size: 28

covid.enabledCounties:
  appling: true
  atkinson: true
  bacon: true
  baker: true
  baldwin: true
  banks: true
  barrow: true
  bartow: true
  ben-hill: true
  berrien: true
  bibb: true
  bleckley: true
  brantley: true
  brooks: true
  bryan: true
  bulloch: true
  burke: true
  butts: true
  calhoun: true
  camden: true
  candler: true
  carroll: true
  catoosa: true
  charlton: true
  chatham: true
  chattahoochee: true
  chattooga: true
  cherokee: true
  clarke: true
  clay: true
  clayton: true
  clinch: true
  cobb: true
  coffee: true
  colquitt: true
  columbia: true
  cook: true
  coweta: true
  crawford: true
  crisp: true
  dade: true
  dawson: true
  dekalb: true
  decatur: true
  dodge: true
  dooly: true
  dougherty: true
  douglas: true
  early: true
  echols: true
  effingham: true
  elbert: true
  emanuel: true
  evans: true
  fannin: true
  fayette: true
  floyd: true
  forsyth: true
  franklin: true
  fulton: true
  georgia: true
  gilmer: true
  glascock: true
  glynn: true
  gordon: true
  grady: true
  greene: true
  gwinnett: true
  habersham: true
  hall: true
  hancock: true
  haralson: true
  harris: true
  hart: true
  heard: true
  henry: true
  houston: true
  irwin: true
  jackson: true
  jasper: true
  jeff-davis: true
  jefferson: true
  jenkins: true
  johnson: true
  jones: true
  lamar: true
  lanier: true
  laurens: true
  lee: true
  liberty: true
  lincoln: true
  long: true
  lowndes: true
  lumpkin: true
  macon: true
  madison: true
  marion: true
  mcduffie: true
  mcintosh: true
  meriwether: true
  miller: true
  mitchell: true
  monroe: true
  montgomery: true
  morgan: true
  murray: true
  muscogee: true
  newton: true
  non-ga: true
  oconee: true
  oglethorpe: true
  paulding: true
  peach: true
  pickens: true
  pierce: true
  pike: true
  polk: true
  pulaski: true
  putnam: true
  quitman: true
  rabun: true
  randolph: true
  richmond: true
  rockdale: true
  schley: true
  screven: true
  seminole: true
  spalding: true
  stephens: true
  stewart: true
  sumter: true
  talbot: true
  taliaferro: true
  tattnall: true
  taylor: true
  telfair: true
  terrell: true
  thomas: true
  tift: true
  toombs: true
  towns: true
  treutlen: true
  troup: true
  turner: true
  twiggs: true
  union: true
  unknown: true
  upson: true
  walker: true
  walton: true
  ware: true
  warren: true
  washington: true
  wayne: true
  webster: true
  wheeler: true
  white: true
  whitfield: true
  wilcox: true
  wilkes: true
  wilkinson: true
  worth: true


---
spring.profiles: cloud

covid:
  index.path: /mnt/data/covid/index.json
  dirs:
    reports:
      root: /mnt/data/reports/
      csv: /mnt/data/reports/v2/csv/
      json: /mnt/data/reports/v2/json/
      histogram: /mnt/data/reports/v2/histogram
      aggregate: /mnt/data/reports/v2/aggregate
    raw:
      v0: /mnt/data/raw/v0
      v1: /mnt/data/raw/v1
      v2: /mnt/data/raw/v2
      manual: /mnt/data/raw/manual
    filtered:
      epicurve.v1: /mnt/data/filteredjson/epicurve/v1
      epicurve.v2: /mnt/data/filteredjson/epicurve/v2
      healthcare: /mnt/data/filteredjson/healthcare
      overview.v1: /mnt/data/filteredjson/overview/v1
      testingstats.v1: /mnt/data/filteredjson/testingstats/v1
      countyOverview.v1: /mnt/data/filteredjson/countyoverview/v1
server.port: 8080
logging.file.path: /mnt/data/covid/logs/

---
spring.profiles: local

covid:
  index.path: H:\dev\workingdir\covid\index.json
  dirs:
    reports:
      root: H:\dev\workingdir\covid\reports
      csv: H:\dev\workingdir\covid\reports\csv
      json: H:\dev\workingdir\covid\reports\json
      histogram: H:\dev\workingdir\covid\reports\histogram
      aggregate: H:\dev\workingdir\covid\reports\aggregate
    raw:
      v0: H:\dev\workingdir\covid\raw\v0
      v1: H:\dev\workingdir\covid\raw\v1
      v2: H:\dev\workingdir\covid\raw\v2
      manual: H:\dev\workingdir\covid\raw\manual
    filtered:
      epicurve.v1: H:\dev\workingdir\covid\filtered\epicurve\v1
      epicurve.v2: H:\dev\workingdir\covid\filtered\epicurve\v2
      healthcare: H:\dev\workingdir\covid\filtered\healthcare
      overview.v1: H:\dev\workingdir\covid\filtered\overview\v1
      testingstats.v1: H:\dev\workingdir\covid\filtered\testingstats\v1
      countyOverview.v1: H:\dev\workingdir\covid\filtered\countyoverview\v1
server.port: 8080
logging.file.path: H:\dev\covid\logs\